<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta name="theme-color" content="#142b27"><meta name="description" content="Informations sur la confidentialité, les données personnelles et vos droits sur E-Vitrine."><title>Confidentialité & RGPD | E-Vitrine</title><link rel="stylesheet" href="/assets/style.css"><script src="/assets/script.js" defer></script></head><body><header class="site-header">
        <a class="brand" href="/" aria-label="E-Vitrine - Accueil">
            <img src="/assets/img/logo-evitrine-vert.svg" alt="Logo E-Vitrine" class="logo">
            <span>E-Vitrine</span>
        </a>
        <!-- Toggle the mobile navigation menu on small screens. -->
        <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-navigation" aria-label="Ouvrir le menu">
            <span></span><span></span><span></span>
        </button>
        <nav id="site-navigation" aria-label="Navigation principale">
            <ul>
                <li><a href="/">Accueil</a></li>
                <li><a href="/offres">Nos offres</a></li>
                <li><a href="/services">Services</a></li>
                <li><a href="/connexion">Mes espaces</a></li>
                <li><a href="/contact" class="contact-link">Parlons de votre projet</a></li>
            </ul>
        </nav>
    </header><section class="page-hero"><p class="eyebrow">E-Vitrine · Bruxelles, Belgique</p><h1>Confidentialité & RGPD</h1><p>Comprendre quelles informations sont utilisées, pourquoi et comment exercer vos droits.</p></section>
<main class="privacy-layout" id="contenu"><aside class="privacy-summary" aria-label="Sommaire"><strong>Sur cette page</strong><a href="#responsable">Le responsable</a><a href="#donnees">Vos données</a><a href="#conservation">Conservation</a><a href="#prestataires">Services externes</a><a href="#stockage">Stockage local</a><a href="#droits">Vos droits</a></aside><article class="privacy-content">
<div class="privacy-draft"><strong>Version préparatoire — à compléter avant publication</strong><p>Le responsable est identifié sous le nom E-Vitrine. Son adresse professionnelle, les prestataires et les durées de conservation restent à compléter. Cette page décrit la version actuelle du site ; elle ne constitue pas une certification de conformité.</p></div>
<p class="privacy-date">Dernière mise à jour : 22 septembre 2026</p>
<section id="responsable"><h2>1. Qui est responsable ?</h2><p>E-Vitrine est le nom utilisé pour ce projet de création de sites web à Bruxelles, en Belgique.</p><dl><dt>Responsable du traitement</dt><dd><strong>E-Vitrine</strong>. Si ce nom est une enseigne commerciale, le nom légal de la personne ou de l’entreprise qui l’exploite doit également être précisé.</dd><dt>Adresse professionnelle</dt><dd>Adresse complète et code postal : <strong>à compléter</strong>, Bruxelles, Belgique.</dd><dt>Contact relatif à vos données</dt><dd><a href="mailto:info@e-vitrine.com">info@e-vitrine.com</a> — fonctionnement de cette boîte à confirmer avant publication.</dd></dl></section>
<section id="donnees"><h2>2. Quelles données et pour quoi faire ?</h2><h3>Votre demande de contact</h3><p>Le formulaire recueille votre nom ou activité, votre adresse e-mail, le type de projet et votre message. Le téléphone est facultatif. Lorsque vous cliquez sur « Envoyer ma demande », ces données sont enregistrées dans la base E-Vitrine et deviennent accessibles au gestionnaire dans son espace privé. Aucun e-mail automatique n’est envoyé.</p><p>Une demande de devis est traitée pour préparer une éventuelle prestation à votre initiative (mesures précontractuelles, article 6.1.b du RGPD). Les autres questions relèvent de l’intérêt légitime à répondre aux personnes qui nous contactent (article 6.1.f). Aucune inscription publicitaire n’est associée au formulaire.</p><h3>Comptes et suivi de projet</h3><p>Les comptes utilisent une adresse e-mail, un mot de passe haché et un rôle d’accès. Les projets, étapes et messages servent au suivi de la prestation. Chaque client accède uniquement aux projets qui lui sont attribués ; les notes et tâches personnelles sont réservées à leur gestionnaire.</p><h3>Sécurité</h3><p>Des compteurs temporaires, associés à une empreinte de l’adresse IP ou de l’adresse e-mail selon l’action, limitent les tentatives de connexion et les envois abusifs. Le serveur peut aussi enregistrer des journaux techniques. Ces traitements reposent sur l’intérêt légitime à protéger le service. Le code ne réalise ni profilage publicitaire ni décision automatisée à votre sujet.</p></section>
<section id="conservation"><h2>3. Combien de temps ?</h2><ul><li><strong>Demandes, comptes, projets et messages :</strong> conservés dans la base jusqu’à suppression par le gestionnaire. Les durées opérationnelles et la procédure de purge doivent être définies avant publication ; aucune purge automatique de ces données n’est encore activée.</li><li><strong>Session privée :</strong> déconnexion après 30 minutes d’inactivité ou 8 heures au maximum. Le cookie est un cookie de session ; son comportement à la fermeture dépend aussi des réglages du navigateur.</li><li><strong>Compteurs de sécurité :</strong> fenêtres de 1 ou 15 minutes selon l’action ; suppression des compteurs expirés depuis plus de 24 heures lors d’une nouvelle action soumise à limitation.</li><li><strong>Journaux et sauvegardes :</strong> durées, rotation et règles d’archivage à confirmer avec l’hébergeur avant publication.</li></ul></section>
<section id="prestataires"><h2>4. Destinataires et services externes</h2><p>La version de développement fonctionne sur cet ordinateur avec Apache, PHP et MySQL de WampServer. Les demandes sont destinées au gestionnaire E-Vitrine. L’hébergement public, les sauvegardes et le fournisseur de messagerie restent à choisir et à documenter avant publication.</p><p>Les scripts et styles du site sont servis localement, sans bibliothèque Supabase ni CDN. Les liens externes conduisent vers des services soumis à leurs propres politiques.</p><p>Le concept « Pause Snack » contient une carte OpenStreetMap qui ne se charge qu’après un clic sur « Afficher la carte ». Son chargement communique notamment l’adresse IP et des informations techniques au service cartographique.</p><p>Les pays de traitement, sous-traitants et éventuels transferts hors de l’Espace économique européen devront être vérifiés et leurs garanties précisées avant la mise en ligne publique.</p></section>
<section id="stockage"><h2>5. Cookies et stockage du navigateur</h2><p>Le cookie de session <code>EVSESSION</code> sert à protéger les formulaires et maintenir votre connexion. Il n’est pas accessible aux scripts JavaScript ; en production HTTPS, il n’est transmis que par une connexion sécurisée. Aucun outil publicitaire ou de mesure d’audience n’est intégré.</p><p>L’ancien stockage de démonstration <code>evitrine.workspace.demo.v1</code> n’est plus utilisé. Si vous avez testé l’ancienne version, vous pouvez supprimer ses données depuis les réglages de votre navigateur.</p><p>Si des traceurs non strictement nécessaires sont ajoutés, un choix préalable permettant de refuser aussi facilement que d’accepter devra être prévu. Voir les <a href="https://autoriteprotectiondonnees.be/citoyen/themes/internet/cookies">explications de l’APD sur les cookies et autres traceurs</a>.</p></section>
<section id="droits"><h2>6. Vos droits et votre contact</h2><p>Selon le traitement et les conditions prévues par le RGPD, vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité de vos données, et vous opposer aux traitements fondés sur l’intérêt légitime. Lorsqu’un traitement repose sur le consentement, vous pouvez le retirer pour l’avenir.</p><p>Adressez votre demande à <a href="mailto:info@e-vitrine.com?subject=Demande%20relative%20%C3%A0%20mes%20donn%C3%A9es">info@e-vitrine.com</a>, en précisant votre demande et les informations permettant de retrouver l’échange. N’envoyez pas spontanément de pièce d’identité ; une vérification proportionnée pourra être demandée en cas de doute.</p><p>Le délai de réponse est en principe d’un mois, avec une prolongation possible de deux mois selon la complexité ou le nombre de demandes, après information dans le premier mois. Consultez les <a href="https://www.autoriteprotectiondonnees.be/quels-sont-mes-droits">droits expliqués par l’APD</a>.</p><p>Vous pouvez également <a href="https://autoriteprotectiondonnees.be/citoyen/agir/introduire-une-plainte">introduire une réclamation auprès de l’Autorité de protection des données belge</a>.</p></section>
<section><h2>7. Évolution de cette page</h2><p>Cette information sera revue lors de la mise en ligne publique, de l’ajout d’un service ou de la modification du formulaire. Les données de facturation et l’exécution d’un contrat devront être couvertes par une information complémentaire si ces traitements sont mis en place.</p><p>Référence : <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj?locale=fr">Règlement (UE) 2016/679, notamment articles 6, 12 et 13</a>.</p></section></article></main><footer><p>© 2026 E-Vitrine. Tous droits réservés.</p><p><a href="/rgpd" aria-current="page">Confidentialité & RGPD</a> · <a href="/contact">Contact</a></p></footer></body></html>